from tkinter import *

#获取各个输入框的数据
def call_back():
    get1=int(intext1.get())
    get2=int(intext2.get())
    get3=intext3.get()
    get4=intext4.get()
    get5=intext5.get()
    get6=intext6.get()
    get7=intext7.get()



root=Tk()
root.title('智龙查询工具')
root.geometry()
fm1=Frame(root)
Label(fm1,text='\n智龙查询工具\n',font='50').pack()
fm1.pack(side=TOP)

fm2=Frame(root)
fm2.pack(side=TOP)
intext1 = Entry(fm2,bd=3,width=10)
intext2 = Entry(fm2,bd=3,width=10)
intext3 = Entry(fm2,bd=3,width=10)
intext4 = Entry(fm2,bd=3,width=10)
intext5 = Entry(fm2,bd=3,width=10)
intext6 = Entry(fm2,bd=3,width=10)
intext7 = Entry(fm2,bd=3,width=10)
intext1.insert(END,'1')
intext2.insert(END,'0')
intext3.insert(END,'100')
intext4.insert(END,'200')
intext5.insert(END,'643')
intext6.insert(END,'3930')
intext7.insert(END,'643')
lab_1=Label(fm2,text = '1编号2石头3单宠4双宠5三宠6四宠7宠物+石头')
lab_2=Label(fm2,text = '只要编号1')
lab_3=Label(fm2,text = '账号编号 最小石头 宠物编号1')
lab_4=Label(fm2,text = '最大石头 宠物编号2')
lab_5=Label(fm2,text = '宠物编号3')
lab_6=Label(fm2,text = '宠物编号4')
lab_7=Label(fm2,text = '宠物+石头的宠物编号')
intext1.grid(row=0,column=1)
intext2.grid(row=1,column=1)
intext3.grid(row=2,column=1)
intext4.grid(row=3,column=1)
intext5.grid(row=4,column=1)
intext6.grid(row=5,column=1)
intext7.grid(row=6,column=1)
lab_1.grid(row=0,column=2)
lab_2.grid(row=1,column=2)
lab_3.grid(row=2,column=2)
lab_4.grid(row=3,column=2)
lab_5.grid(row=4,column=2)
lab_6.grid(row=5,column=2)
lab_7.grid(row=6,column=2)
bt1=Button(fm2,bd=3,command=call_back,text='开始查询',width=10)
bt2=Button(fm2,bd=3,command=root.quit,text='退出',width=10)
bt1.grid(row=7,column=1)
bt2.grid(row=7,column=2)
fm3=Frame(root)
fm3.pack(side=TOP)
lab_8=Label(fm3,text = '\n查询结果\n',font="50").pack()
out_text=Text(fm3)
out_text.pack()


root.mainloop()